---
- name: Configure AAP Controller
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aap_organizations:
      - name: "GitOps_Managed_Org"
        description: "Organization managed strictly by infra.aap_configuration via GitHub"
        state: present

  roles:
    - role: infra.aap_configuration.dispatch

